giantswarm/app

- README.md
Align the CircleCI badge style with other repository
Before:
After:
> Update circleci badge to shield

- CHANGELOG.md
- go.mod
- go.sum
- pkg/key/app.go
Towards giantswarm/giantswarm#11656
> Add key funcs for app labels

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
- pkg/validation/error.go
- pkg/validation/error_test.go
Towards https://github.com/giantswarm/giantswarm/issues/11656
> Return separate validation errors for kubeconfig and config map not found

- CHANGELOG.md
- go.mod
- go.sum
- pkg/app/app.go
Towards https://github.com/giantswarm/giantswarm/issues/14603
> Add config-controller version label ; Add ConfigMajorVersion

- CHANGELOG.md
- go.mod
- go.sum
- pkg/app/app.go
- pkg/validation/app.go
- pkg/validation/app_test.go
- pkg/validation/error.go
Towards https://github.com/giantswarm/giantswarm/issues/14604
Towards https://github.com/giantswarm/giantswarm/issues/14603
> Validate App CR cm/secret if managed by config-controller

- CHANGELOG.md
- pkg/validation/error.go
Towards https://github.com/giantswarm/giantswarm/issues/14993
> Remove unused errors from validation package

- CHANGELOG.md
- pkg/app/app.go
Towards https://github.com/giantswarm/giantswarm/issues/15075
> Do not set config-controller.giantswarm.io/version label

- CHANGELOG.md
- pkg/annotation/annotation.go
- pkg/key/appcatalogentry.go
Towards https://github.com/giantswarm/giantswarm/issues/14846
> Add team support for AppCatalogEntry CRs

- CHANGELOG.md
- go.mod
- go.sum
- pkg/validation/app.go
- pkg/validation/app_test.go
Toward https://github.com/giantswarm/giantswarm/issues/15852
Only Namespace constraints are implemented.
> Check namespace constraints using appCatalogEntry CRs

- CHANGELOG.md
- pkg/annotation/annotation.go
- pkg/key/appcatalogentry.go
Towards https://github.com/giantswarm/giantswarm/issues/14846
> Add owners annotation

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
- pkg/validation/validator.go
Toward https://github.com/giantswarm/giantswarm/issues/15852
> Check provider constraints

- CHANGELOG.md
- pkg/key/app.go
Towards https://github.com/giantswarm/giantswarm/issues/16061
> Add key.AppTeam function

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards https://github.com/giantswarm/giantswarm/issues/16432
> Add validation for user configmap and secret names for default apps

- CHANGELOG.md
- go.mod
- go.sum
- pkg/key/app.go
Towards https://github.com/giantswarm/giantswarm/issues/13746
>  Add InstallSkipCRDs key function for app CRs

- CHANGELOG.md
- pkg/key/catalog.go
- pkg/key/catalog_test.go
Toward https://github.com/giantswarm/roadmap/issues/219
> Add catalog CRD key functions

- go.mod
- go.sum
- pkg/crd/crd.go
- pkg/crd/error.go
Toward https://github.com/giantswarm/roadmap/issues/219
> Add crd package

- CHANGELOG.md
- pkg/key/app.go
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards https://github.com/giantswarm/giantswarm/issues/18384
> Validate Catalog CRs instead of AppCatalog CRs in App validation

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards https://github.com/giantswarm/giantswarm/issues/18349
> Don't restrict user values configmap name for NGINX IC

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
- pkg/validation/validator.go
The old flag's name is not accurate, so this PR changes it.
> Replace `validateResourcesExist` with the `enableManagedByLabel` flag

- CHANGELOG.md
- pkg/key/cluster.go
- pkg/validation/app.go
Towards: https://github.com/giantswarm/app-admission-controller/pull/226
> Adjusting functions for org-namespaced apps

- CHANGELOG.md
- pkg/key/appcatalogentry.go
Towards https://github.com/giantswarm/giantswarm/issues/21246
This is for filtering app catalog entry CRs in https://github.com/giantswarm/app-operator/pull/966
> Add key.AppCatalogEntryCompatibleProviders

- .nancy-ignore
- CHANGELOG.md
- pkg/crd/crd.go
Towards https://github.com/giantswarm/giantswarm/issues/21782
> Ensure `application.giantswarm.io` CRDs from `apiextensions-application`

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
> Add base for unique in-cluster app name validation

- CHANGELOG.md
- go.mod
- go.sum
- pkg/key/app.go
- pkg/key/app_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/23699
> Adding support for timeout option in App CRs

- pkg/key/app_test.go
Fixing tests names. No changes to the logic.
> Renaming tests

- pkg/key/app.go
- pkg/key/appcatalog.go
- pkg/key/catalog.go
- pkg/validation/app.go
Closes https://github.com/giantswarm/giantswarm/issues/32975
> Adapt for golangci-lint v2
