giantswarm/app

- pkg/app/app.go
Toward https://github.com/giantswarm/giantswarm/issues/8082
It would upgrade the helm chart in a failed state forecefully.
> Chart operator helm force upgrade

- pkg/app/app.go
So that we can configure namespace, where the chart should be installed.
E.g. I'm moving cert-manager into app collection and we install it into kube-system namespace. For monitoring apps it would be monitoring namespace
> Add appNamespace support

- pkg/app/app.go
For stateful apps like prometheus it is better to disable forced upgrades so that we don't delete all the resources on failure
> Add option to disable force helm upgrade

- CHANGELOG.md
- README.md
- pkg/app/app.go
Towards https://github.com/giantswarm/giantswarm/issues/10973
~~Adds a new parameter so it can be used in opsctl.~~
Sets `app-operator.giantswarm.io/version`to  `0.0.0` for use in opsctl.
> Set version label value to 0.0.0 for use in opsctl

- CHANGELOG.md
- pkg/key/app.go
- pkg/key/cluster.go
Some extra key funcs needed for https://github.com/giantswarm/app-admission-controller/pull/19
> Add key functions for cluster configmap and kubeconfig names

- CHANGELOG.md
- pkg/app/app.go
Towards: https://github.com/giantswarm/giantswarm/issues/14557
Allow configuration of user configmap and secret in app CRs.
> add configmap and secret

- CHANGELOG.md
- pkg/key/chart.go
- pkg/key/chart_test.go
Towards https://github.com/giantswarm/giantswarm/issues/14163
We already have `key.ToApp`. This adds `key.ToChart` which will be used in the chart CR watcher in app-operator.
> Add key.ToChart function

- CHANGELOG.md
- go.mod
- go.sum
- pkg/key/app.go
- pkg/validation/app.go
- pkg/validation/app_test.go
Toward giantswarm/giantswarm#16209
My original plan was to check the target namespace object but I realized app-admission-controller can't fetch any objects from workload clusters. So I check app CRs with the same target namespace instead.
> Validate namespaceConfig with the apps that sharing the target namespace

- pkg/key/app.go
Updates the catalog domain to giantswarm.github.io instead of giantswarm.github.com. Towards giantswarm/giantswarm#15898
> Update catalog domain to github.io

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards https://github.com/giantswarm/giantswarm/issues/16713
Validates the length of the app name. As if it's more than 53 chars it will fail due to a limit in the helm release name length.
> Add validation for length of metadata.name

- CHANGELOG.md
- go.mod
- go.sum
- pkg/app/app.go
- pkg/key/app.go
- pkg/key/appcatalog.go
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards https://github.com/giantswarm/giantswarm/issues/16893
Swapping to the new library to simplify the dependency graph. The app library also has an annotation and label package. Will move these to k8smetadata as a later change.
> Use labels and annotations from k8smetadata not apiextensions

- CHANGELOG.md
- go.mod
- pkg/validation/app.go
- pkg/values/configmap.go
- pkg/values/configmap_test.go
- pkg/values/secret.go
- pkg/values/secret_test.go
- pkg/values/values.go
This is just prep for using the Catalog CRD in https://github.com/giantswarm/kubectl-gs/pull/365 because it uses the values package.
@tomahawk28 This is a breaking change but WDYT can we just do a major version bump?
> Replace AppCatalog with Catalog CRD in values package

- CHANGELOG.md
- pkg/crd/crd.go
Toward giantswarm/roadmap#219
At some points, we need to load whole CRDs from the github, such as opsctl. https://github.com/giantswarm/opsctl/blob/3d77e8098250de3b70cc188504c3897937e5d30b/command/ensure/crds/command.go#L234-L264
> Add another LoadCRDs function

- pkg/key/app.go
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards giantswarm/giantswarm#18349
In https://github.com/giantswarm/app-admission-controller/pull/155 we will always default the version to the correct value if its 1.0.0.
This extends the validation rules so if the defaulting fails we reject the CR.
> Reject app version label with legacy 1.0.0 value

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards giantswarm/giantswarm#18349
> Check for nil or empty .metadata.name in catalog validation

- CHANGELOG.md
- pkg/app/app.go
Instead of hard-coding the app CR namespace to `giantswarm`, make it configurable and use `giantswarm` as default to not break things. I need this to enable opsctl to deploy app to workload clusters, see https://github.com/giantswarm/opsctl/pull/1219
> make app CR namespace configurable

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
When "in cluster" is false we  validate that `.spec.kubeConfig.secret.namespace` is set but not `.spec.kubeConfig.secret.name`.
This results in a strange error in the clients resource. This adds the missing validation.
```
E 11/08 14:43:43 default/hello-world clients retrying due to error | operatorkit/v5/pkg/resource/wrapper/retryresource/basic_resource.go:83 | controller=app-operator-app | event=delete | loop=52 | stack=map[annotation:resource name may not be empty kind:unknown stack:[map[file:/go/pkg/mod/github.com/giantswarm/kubeconfig/v4@v4.1.0/kubeconfig.go line:122] map[file:/go/pkg/mod/github.com/giantswarm/kubeconfig/v4@v4.1.0/kubeconfig.go line:45] map[file:/root/project/service/internal/clientcache/cache.go line:138] map[file:/root/project/service/internal/clientcache/cache.go …
```
> Validate kubeconfig secret name is set

- CHANGELOG.md
- pkg/key/app.go
- pkg/validation/app.go
- pkg/validation/app_test.go
- pkg/validation/validator.go
Towards https://github.com/giantswarm/giantswarm/issues/19700
Related to https://github.com/giantswarm/workload-clusters-fleet-demo/pull/1
We can simplify our Flux setup to include user values configmaps and secrets in the same directory as the app CR.
To do this we loosen the validation in app-admission-controller if the label `giantswarm.io/managed-by` is set to `flux`.
We keep the logic in the validation resource in app-operator which sets the app CR status.
> Skip validation of app dependencies when managed-by label equals flux

- CHANGELOG.md
- pkg/app/app.go
Towards https://github.com/giantswarm/giantswarm/issues/19942
When using `opsctl deploy` with the `--cluster` flag for workload cluster apps we need to set inCluster to false.
> Allow setting `.spec.kubeConfig.inCluster` when generating app CRs

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
Towards giantswarm/giantswarm#20153
Error message includes target namespace to differentiate from the namespace of the app CR.
```
target namespace for app `nginx-ingress-controller-app` cannot be changed from `kube-system` to `default`
```
```
kubectl patch app -n xk38a nginx-ingress-controller-app --type='json' -p '[{
"op": "replace",
"path": "/spec/namespace",
"value": "default"
}]'
Error from server: admission webhook "apps.app-admission-controller.giantswarm.io" denied the request: validation error: target namespace for app `nginx-ingress-controller-app` cannot be changed from `kube-system` to `default`
```
> Add ValidateAppUpdate to ensure .spec.namespace is immutable

- pkg/validation/app.go
- pkg/validation/app_test.go
Related issue: https://github.com/giantswarm/giantswarm/issues/19485
This PR introduces restrictions on the `.spec.namespace`, so users won't be able to exploit it to install apps outside their namespaces and clusters.
1. This App CR is NOT accepted:
```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
name: hello-world
namespace: c2fv2
spec:
catalog: giantswarm
name: hello-world-app
version: 0.1.0
namespace: kube-system
kubeConfig:
inCluster: true
```
with the error:
```
Error from server: error when creating "app.yaml": admission webhook "apps.app-admission-controller.giantswarm.io" denied the request: validation error: target namespace kube-system is not allowed
```
2. This App CR is accepted as it goes to the WC:
```yaml
apiVersion: …
```
> Validating target namespace

- CHANGELOG.md
- pkg/key/chart.go
Towards giantswarm/giantswarm#20331
When managing app CRs with default-apps-openstack we use the the cluster ID as a prefix. However for the chart CRs in the workload cluster we need to remove the cluster ID.
> Add key.ChartName for formatting chart CR name

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
- pkg/validation/validator.go
The code has been moved here from the `app-admission-controller`, see related PR [here](https://github.com/giantswarm/app-admission-controller/pull/217).
Important changes:
* `conditional` flag has been added to the `Validator`. I made the flag's name general and not related to Flux in particular in order to make it suitable for other use cases as well. At the moment it's used for conditional execution of `key.IsManagedByFlux` only,
* checking ConfigMaps and Secrets have been been moved to separate methods,
* `key.IsManagedByFlux` has been moved to the aforementioned methods and limited only to skipping the existence validation.
> Skipping CM and Secret validation for Flux-managed Apps

- CHANGELOG.md
- pkg/key/app.go
- pkg/validation/app.go
- pkg/validation/app_test.go
App CRs living in the org namespace are going to have different logic applied in comparison to the App CRs living in the cluster namespace. Continuation of the https://github.com/giantswarm/giantswarm/issues/20443 issue and the https://github.com/giantswarm/kubectl-gs/pull/639 PR.
> Validating labels for both cluster-managed and org-managed App CRs

- .nancy-ignore
- CHANGELOG.md
- pkg/crd/crd.go
This reverts commit ef13285230e26210712712f05657cce2eee25cbe.
Apparently there is a "hack" script that pulls changes from other repos to apiextensions :rage1:
> Revert "Ensure `application.giantswarm.io` CRDs from `apiextensions-application` (#246)"

- pkg/key/cluster.go
- pkg/key/cluster_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/23333
Apps for CAPx created in the `org-*` namespace cannot rely on the `ingress-controller-values` ConfigMap because nothing seems to create it for these apps, it seems such functionality is currently offered only to the vintage clusters via [cluster-operator](https://github.com/giantswarm/cluster-operator/blob/507d3528dd0d32e9134941632e4d56499c59638b/service/controller/resource/clusterconfigmap/desired.go#L131). This functionality does not seem to be implemented in the CAPx components, hence this slight change of order will allow org-namespaced NGINX apps to use the standard `%s-cluster-values` ConfigMap.
> Changing order of conditions when getting cluster values for App CR

- pkg/validation/app.go
- pkg/validation/app_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/25628
> Extending checks allowing user ConfigMap and Secrets names without `Cluster_ID` prefix even when App CR name carries it.

- .nancy-ignore
- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
This PR re-works most of the changes introduced by Atlas in [this PR](https://github.com/giantswarm/app/pull/266). The solution introduced in there accounts for ORG namespace, but takes care only for cluster singletons, and does nothing for the namespace singletons. But more importantly, I believe, it does it the wrong way, I mean, all the apps are selected and then when being inspected we make sure we are not looking at the "wrong" ones, i.e., coming from the other clusters. While we should rather make sure we are not selecting the other clusters' apps, and then check them as usual without extra conditions imposed. So I restored the previous code and instead introduced label selector. 
I also re-worked the nested IF statements to make it more flat, it feels more readable this way, but if …
> Introducing label selector

- CHANGELOG.md
- pkg/validation/app.go
- pkg/validation/app_test.go
I think people are not obliged to put the cluster label on the legacy clusters' apps. If so, then error message needs to be fixed because otherwise it may sometimes return an empty cluster id.
> Fixing ID part

- CHANGELOG.md
- pkg/validation/app.go
I made a mistake when restoring older configuration and copied too much. Using `.spec.name` makes both AppOp and AppAdmissionCtrl to pick up app being submitted / processed.
Towards: https://giantswarm.app.opsgenie.com/alert/detail/f8b03c8b-22a3-4393-b445-466ac9269f57-1678442118383/details
> Fixing field selector

- CHANGELOG.md
- pkg/key/cluster.go
- pkg/key/cluster_test.go
- pkg/validation/app.go
- pkg/validation/app_test.go
Those exceptions can safely be removed since neither the `nginx-ingress-controller-app` nor its successor `ingress-nginx` do rely on the `ingress-controller-values` `ConfigMap` anymore. The included `configmap.proxy-protocol` key is automatically determined for a long time now and versions still requiring it are using an image which is not supported with Kubernetes versions included in current `cluster-operator` versions.
Like: New `cluster-operator` versions including this change come with recent Kubernetes versions. Old `nginx-ingress-controller-app` versions still relying on the `ingress-controller-values` `ConfigMap` might not be supported with those Kubernetes versions.
> App: Remove `nginx-ingress-controller-app` exceptions.

- pkg/key/app.go
- pkg/key/app_test.go
- pkg/values/configmap.go
- pkg/values/configmap_test.go
- pkg/values/secret.go
- pkg/values/secret_test.go
Towards: https://github.com/giantswarm/adidas/issues/1326
This PR introduces two functions in the `pkg/key` package, the `ConfigMapExtraConfigs` and the `SecretExtraConfigs`, for getting ConfigMaps and Secrets from the extra configs list respectively, and updates the `pkg/values` package to use them.
> Adding SecretExtraConfig and ConfigMapExtraConfig
